# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- releases/*

pr: none

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
      Python37:
        python.version: '3.7'
        
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

- script: |
    python -m pip install --upgrade pip
    rm -r sdk
    pip install openapi-generator-cli    
    python -m openapi-generator generate --generator-name python --input-spec openapi.json --output sdk  --package-name autharmor_python --package-version $(PACKAGE_VERSION)
  displayName: 'Generate SDK dist'

- script: |
    echo "Yet to be implemented - requires extensive testing"
  displayName: 'Modify SDK setup file'

- script: |
    python -m pip install --upgrade pip
    cd sdk
    pip install -r requirements.txt
    pip install build
    python -m build
  displayName: 'Build SDK dist'

- script: |
    python -m twine upload --repository testpypi ./sdk/dist/* --verbose  --username __token__ --password $(TEST_PYPI_API_TOKEN)
  displayName: 'Deploy SDK dist to testpypi'

# - script: |
#     python -m twine upload --repository pypi ./sdk/dist/* --verbose  --username __token__ --password $(Build.PROD_PYPI_API_TOKEN)
#   displayName: 'Deploy SDK dist to pypi'

- script: |
    pip install -i https://test.pypi.org/simple/ autharmor-python
    # pip install autharmor-python
  displayName: 'Test install for logs'