# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.validate_magiclink_email_registration_request import ValidateMagiclinkEmailRegistrationRequest  # noqa: E501

class TestValidateMagiclinkEmailRegistrationRequest(unittest.TestCase):
    """ValidateMagiclinkEmailRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMagiclinkEmailRegistrationRequest:
        """Test ValidateMagiclinkEmailRegistrationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMagiclinkEmailRegistrationRequest`
        """
        model = ValidateMagiclinkEmailRegistrationRequest()  # noqa: E501
        if include_optional:
            return ValidateMagiclinkEmailRegistrationRequest(
                registration_validation_token = '',
                ip_address = '',
                user_agent = ''
            )
        else:
            return ValidateMagiclinkEmailRegistrationRequest(
        )
        """

    def testValidateMagiclinkEmailRegistrationRequest(self):
        """Test ValidateMagiclinkEmailRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
