# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.auth_method_use_type_response import AuthMethodUseTypeResponse  # noqa: E501

class TestAuthMethodUseTypeResponse(unittest.TestCase):
    """AuthMethodUseTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthMethodUseTypeResponse(self):
        """Test AuthMethodUseTypeResponse"""
        # inst = AuthMethodUseTypeResponse()

if __name__ == '__main__':
    unittest.main()
