# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.get_users_response import GetUsersResponse  # noqa: E501

class TestGetUsersResponse(unittest.TestCase):
    """GetUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUsersResponse:
        """Test GetUsersResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUsersResponse`
        """
        model = GetUsersResponse()  # noqa: E501
        if include_optional:
            return GetUsersResponse(
                user_records = [
                    autharmor_python.models.user.user(
                        user_id = '', 
                        email_address = '', 
                        username = '', 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                page_info = autharmor_python.models.users_response_page_info.users_response_page_info(
                    currnet_page_number = 56, 
                    currnet_page_size = 56, 
                    total_page_count = 56, 
                    total_record_count = 56, )
            )
        else:
            return GetUsersResponse(
        )
        """

    def testGetUsersResponse(self):
        """Test GetUsersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
