# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.signing_method import SigningMethod  # noqa: E501

class TestSigningMethod(unittest.TestCase):
    """SigningMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSigningMethod(self):
        """Test SigningMethod"""
        # inst = SigningMethod()

if __name__ == '__main__':
    unittest.main()
