# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.resident_key_requirement_type import ResidentKeyRequirementType  # noqa: E501

class TestResidentKeyRequirementType(unittest.TestCase):
    """ResidentKeyRequirementType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResidentKeyRequirementType(self):
        """Test ResidentKeyRequirementType"""
        # inst = ResidentKeyRequirementType()

if __name__ == '__main__':
    unittest.main()
