# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.autharmor_api import AutharmorApi  # noqa: E501


class TestAutharmorApi(unittest.TestCase):
    """AutharmorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutharmorApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_auth_auth_request_id_get(self) -> None:
        """Test case for v4_auth_auth_request_id_get

          Get Auth Info  # noqa: E501
        """
        pass

    def test_v4_auth_authenticator_start_post(self) -> None:
        """Test case for v4_auth_authenticator_start_post

          Start auth request using Authenticator  # noqa: E501
        """
        pass

    def test_v4_auth_authenticator_validate_post(self) -> None:
        """Test case for v4_auth_authenticator_validate_post

         Validate auth request for Auth Armor Authenticator  # noqa: E501
        """
        pass

    def test_v4_auth_magiclink_email_start_post(self) -> None:
        """Test case for v4_auth_magiclink_email_start_post

          Start auth request using Maigclink Email  # noqa: E501
        """
        pass

    def test_v4_auth_magiclink_email_validate_post(self) -> None:
        """Test case for v4_auth_magiclink_email_validate_post

          Validate auth request for Magiclink Email  # noqa: E501
        """
        pass

    def test_v4_auth_webauthn_finish_post(self) -> None:
        """Test case for v4_auth_webauthn_finish_post

          Finish auth request using WebAuthn  # noqa: E501
        """
        pass

    def test_v4_auth_webauthn_start_post(self) -> None:
        """Test case for v4_auth_webauthn_start_post

         Start auth request using Webauthn  # noqa: E501
        """
        pass

    def test_v4_auth_webauthn_validate_post(self) -> None:
        """Test case for v4_auth_webauthn_validate_post

          Validate auth request for WebAuthn  # noqa: E501
        """
        pass

    def test_v4_users_get(self) -> None:
        """Test case for v4_users_get

          Get Users  # noqa: E501
        """
        pass

    def test_v4_users_registrations_authenticator_registration_id_validate_post(self) -> None:
        """Test case for v4_users_registrations_authenticator_registration_id_validate_post

          Validate User Registration for Authenticator  # noqa: E501
        """
        pass

    def test_v4_users_registrations_authenticator_start_post(self) -> None:
        """Test case for v4_users_registrations_authenticator_start_post

          Start User Registration for Authenticator  # noqa: E501
        """
        pass

    def test_v4_users_registrations_magiclink_email_registration_id_validate_post(self) -> None:
        """Test case for v4_users_registrations_magiclink_email_registration_id_validate_post

          Validate MagicLink Registration Token  # noqa: E501
        """
        pass

    def test_v4_users_registrations_magiclink_email_start_post(self) -> None:
        """Test case for v4_users_registrations_magiclink_email_start_post

          Start User Registration for MagicLink  # noqa: E501
        """
        pass

    def test_v4_users_registrations_registration_id_get(self) -> None:
        """Test case for v4_users_registrations_registration_id_get

          Get Registration Info  # noqa: E501
        """
        pass

    def test_v4_users_registrations_webauthn_registration_id_finish_post(self) -> None:
        """Test case for v4_users_registrations_webauthn_registration_id_finish_post

          Finish WebAuthn Registration for new user  # noqa: E501
        """
        pass

    def test_v4_users_registrations_webauthn_registration_id_validate_post(self) -> None:
        """Test case for v4_users_registrations_webauthn_registration_id_validate_post

          Validate User Registration for WebAuthn  # noqa: E501
        """
        pass

    def test_v4_users_registrations_webauthn_start_post(self) -> None:
        """Test case for v4_users_registrations_webauthn_start_post

          Start WebAuthn Registration for new user  # noqa: E501
        """
        pass

    def test_v4_users_user_id_auth_history_get(self) -> None:
        """Test case for v4_users_user_id_auth_history_get

          Get Auth History for User  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_authenticator_get(self) -> None:
        """Test case for v4_users_user_id_credentials_authenticator_get

          Get Users Authenticator Credential list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_credential_id_disable_post(self) -> None:
        """Test case for v4_users_user_id_credentials_credential_id_disable_post

          Disable Users Credential by Id  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_credential_id_get(self) -> None:
        """Test case for v4_users_user_id_credentials_credential_id_get

          Get Users Credential by Credential ID  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_get(self) -> None:
        """Test case for v4_users_user_id_credentials_get

          Get Users Credentials list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_magiclink_email_get(self) -> None:
        """Test case for v4_users_user_id_credentials_magiclink_email_get

          Get Users Authenticator Credential list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_webauthn_get(self) -> None:
        """Test case for v4_users_user_id_credentials_webauthn_get

          Get Users WebAuthn Device list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_get(self) -> None:
        """Test case for v4_users_user_id_get

          Get User By Id  # noqa: E501
        """
        pass

    def test_v4_users_user_id_magiclink_email_update_start_post(self) -> None:
        """Test case for v4_users_user_id_magiclink_email_update_start_post

          Start Change Users Email Address  # noqa: E501
        """
        pass

    def test_v4_users_user_id_put(self) -> None:
        """Test case for v4_users_user_id_put

          Update User  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_authenticator_start_post(self) -> None:
        """Test case for v4_users_user_id_registrations_authenticator_start_post

          Start Authenticator Registration for existing user  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_magiclink_email_start_post(self) -> None:
        """Test case for v4_users_user_id_registrations_magiclink_email_start_post

          Create Magiclink Email Record for existing user  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_webauthn_registration_id_finish_post(self) -> None:
        """Test case for v4_users_user_id_registrations_webauthn_registration_id_finish_post

          Finish WebAuthn Registration for existing user  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_webauthn_start_post(self) -> None:
        """Test case for v4_users_user_id_registrations_webauthn_start_post

          Start WebAuthn Registration for existing user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
