# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.user_registrations_get_registration_info_api import UserRegistrationsGetRegistrationInfoApi  # noqa: E501


class TestUserRegistrationsGetRegistrationInfoApi(unittest.TestCase):
    """UserRegistrationsGetRegistrationInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserRegistrationsGetRegistrationInfoApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_users_registrations_registration_id_get(self) -> None:
        """Test case for v4_users_registrations_registration_id_get

          Get Registration Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
