# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.start_authenticator_auth_response import StartAuthenticatorAuthResponse  # noqa: E501

class TestStartAuthenticatorAuthResponse(unittest.TestCase):
    """StartAuthenticatorAuthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartAuthenticatorAuthResponse:
        """Test StartAuthenticatorAuthResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartAuthenticatorAuthResponse`
        """
        model = StartAuthenticatorAuthResponse()  # noqa: E501
        if include_optional:
            return StartAuthenticatorAuthResponse(
                auth_validation_token = '',
                auth_request_id = '',
                user_id = '',
                visual_verify_value = '',
                response_code = 56,
                response_message = '',
                qr_code_data = '',
                push_message_sent = True,
                timeout_in_seconds = 56,
                timeout_utc_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return StartAuthenticatorAuthResponse(
        )
        """

    def testStartAuthenticatorAuthResponse(self):
        """Test StartAuthenticatorAuthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
