# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.users_credentials_api import UsersCredentialsApi  # noqa: E501


class TestUsersCredentialsApi(unittest.TestCase):
    """UsersCredentialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersCredentialsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_users_user_id_credentials_authenticator_get(self) -> None:
        """Test case for v4_users_user_id_credentials_authenticator_get

          Get Users Authenticator Credential list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_credential_id_disable_post(self) -> None:
        """Test case for v4_users_user_id_credentials_credential_id_disable_post

          Disable Users Credential by Id  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_credential_id_get(self) -> None:
        """Test case for v4_users_user_id_credentials_credential_id_get

          Get Users Credential by Credential ID  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_get(self) -> None:
        """Test case for v4_users_user_id_credentials_get

          Get Users Credentials list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_magiclink_email_get(self) -> None:
        """Test case for v4_users_user_id_credentials_magiclink_email_get

          Get Users Authenticator Credential list  # noqa: E501
        """
        pass

    def test_v4_users_user_id_credentials_webauthn_get(self) -> None:
        """Test case for v4_users_user_id_credentials_webauthn_get

          Get Users WebAuthn Device list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
