# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.auth_info_api import AuthInfoApi  # noqa: E501


class TestAuthInfoApi(unittest.TestCase):
    """AuthInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthInfoApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_auth_auth_request_id_get(self) -> None:
        """Test case for v4_auth_auth_request_id_get

          Get Auth Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
