# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.authenticator_attachment_type import AuthenticatorAttachmentType  # noqa: E501

class TestAuthenticatorAttachmentType(unittest.TestCase):
    """AuthenticatorAttachmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticatorAttachmentType(self):
        """Test AuthenticatorAttachmentType"""
        # inst = AuthenticatorAttachmentType()

if __name__ == '__main__':
    unittest.main()
