# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.get_registration_info_response import GetRegistrationInfoResponse  # noqa: E501

class TestGetRegistrationInfoResponse(unittest.TestCase):
    """GetRegistrationInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRegistrationInfoResponse:
        """Test GetRegistrationInfoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRegistrationInfoResponse`
        """
        model = GetRegistrationInfoResponse()  # noqa: E501
        if include_optional:
            return GetRegistrationInfoResponse(
                registration_status_name = '',
                registration_status_code = 56,
                auth_method = ''
            )
        else:
            return GetRegistrationInfoResponse(
        )
        """

    def testGetRegistrationInfoResponse(self):
        """Test GetRegistrationInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
