# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.signed_message_type import SignedMessageType  # noqa: E501

class TestSignedMessageType(unittest.TestCase):
    """SignedMessageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignedMessageType(self):
        """Test SignedMessageType"""
        # inst = SignedMessageType()

if __name__ == '__main__':
    unittest.main()
