# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.user_registrations_authenticator_api import UserRegistrationsAuthenticatorApi  # noqa: E501


class TestUserRegistrationsAuthenticatorApi(unittest.TestCase):
    """UserRegistrationsAuthenticatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserRegistrationsAuthenticatorApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_users_registrations_authenticator_registration_id_validate_post(self) -> None:
        """Test case for v4_users_registrations_authenticator_registration_id_validate_post

          Validate User Registration for Authenticator  # noqa: E501
        """
        pass

    def test_v4_users_registrations_authenticator_start_post(self) -> None:
        """Test case for v4_users_registrations_authenticator_start_post

          Start User Registration for Authenticator  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_authenticator_start_post(self) -> None:
        """Test case for v4_users_user_id_registrations_authenticator_start_post

          Start Authenticator Registration for existing user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
