# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.fido2_registration_data import Fido2RegistrationData  # noqa: E501

class TestFido2RegistrationData(unittest.TestCase):
    """Fido2RegistrationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Fido2RegistrationData:
        """Test Fido2RegistrationData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Fido2RegistrationData`
        """
        model = Fido2RegistrationData()  # noqa: E501
        if include_optional:
            return Fido2RegistrationData(
                id = '',
                attestation_object = '',
                client_data = ''
            )
        else:
            return Fido2RegistrationData(
        )
        """

    def testFido2RegistrationData(self):
        """Test Fido2RegistrationData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
