# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.response_auth_method import ResponseAuthMethod  # noqa: E501

class TestResponseAuthMethod(unittest.TestCase):
    """ResponseAuthMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseAuthMethod:
        """Test ResponseAuthMethod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseAuthMethod`
        """
        model = ResponseAuthMethod()  # noqa: E501
        if include_optional:
            return ResponseAuthMethod(
                name = 'MobileDevice',
                usetype = 'biometric'
            )
        else:
            return ResponseAuthMethod(
        )
        """

    def testResponseAuthMethod(self):
        """Test ResponseAuthMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
