# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.request_details import RequestDetails  # noqa: E501

class TestRequestDetails(unittest.TestCase):
    """RequestDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestDetails:
        """Test RequestDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestDetails`
        """
        model = RequestDetails()  # noqa: E501
        if include_optional:
            return RequestDetails(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                auth_profile_details = autharmor_python.models.auth_profile_details.auth_profile_details(
                    user_id = '', 
                    username = '', ),
                origin_location_data = autharmor_python.models.location_data.location_data(
                    latitude = '', 
                    longitude = '', 
                    ip_address = '', ),
                auth_method = 'MobileDevice'
            )
        else:
            return RequestDetails(
        )
        """

    def testRequestDetails(self):
        """Test RequestDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
