# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.enrolled_auth_method import EnrolledAuthMethod  # noqa: E501

class TestEnrolledAuthMethod(unittest.TestCase):
    """EnrolledAuthMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnrolledAuthMethod:
        """Test EnrolledAuthMethod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnrolledAuthMethod`
        """
        model = EnrolledAuthMethod()  # noqa: E501
        if include_optional:
            return EnrolledAuthMethod(
                auth_method_name = '',
                auth_method_id = 56,
                auth_method_masked_info = ''
            )
        else:
            return EnrolledAuthMethod(
        )
        """

    def testEnrolledAuthMethod(self):
        """Test EnrolledAuthMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
