# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.user_registrations_magiclink_email_api import UserRegistrationsMagiclinkEmailApi  # noqa: E501


class TestUserRegistrationsMagiclinkEmailApi(unittest.TestCase):
    """UserRegistrationsMagiclinkEmailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserRegistrationsMagiclinkEmailApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_users_registrations_magiclink_email_registration_id_validate_post(self) -> None:
        """Test case for v4_users_registrations_magiclink_email_registration_id_validate_post

          Validate MagicLink Registration Token  # noqa: E501
        """
        pass

    def test_v4_users_registrations_magiclink_email_start_post(self) -> None:
        """Test case for v4_users_registrations_magiclink_email_start_post

          Start User Registration for MagicLink  # noqa: E501
        """
        pass

    def test_v4_users_user_id_magiclink_email_update_start_post(self) -> None:
        """Test case for v4_users_user_id_magiclink_email_update_start_post

          Start Change Users Email Address  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_magiclink_email_start_post(self) -> None:
        """Test case for v4_users_user_id_registrations_magiclink_email_start_post

          Create Magiclink Email Record for existing user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
