# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.user_verification_requirement_type import UserVerificationRequirementType  # noqa: E501

class TestUserVerificationRequirementType(unittest.TestCase):
    """UserVerificationRequirementType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserVerificationRequirementType(self):
        """Test UserVerificationRequirementType"""
        # inst = UserVerificationRequirementType()

if __name__ == '__main__':
    unittest.main()
