# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.finish_webauthn_auth_response import FinishWebauthnAuthResponse  # noqa: E501

class TestFinishWebauthnAuthResponse(unittest.TestCase):
    """FinishWebauthnAuthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinishWebauthnAuthResponse:
        """Test FinishWebauthnAuthResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinishWebauthnAuthResponse`
        """
        model = FinishWebauthnAuthResponse()  # noqa: E501
        if include_optional:
            return FinishWebauthnAuthResponse(
                auth_validation_token = '',
                user_id = '',
                auth_request_id = '',
                username = ''
            )
        else:
            return FinishWebauthnAuthResponse(
        )
        """

    def testFinishWebauthnAuthResponse(self):
        """Test FinishWebauthnAuthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
