# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.auth_profile_details import AuthProfileDetails  # noqa: E501

class TestAuthProfileDetails(unittest.TestCase):
    """AuthProfileDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthProfileDetails:
        """Test AuthProfileDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthProfileDetails`
        """
        model = AuthProfileDetails()  # noqa: E501
        if include_optional:
            return AuthProfileDetails(
                user_id = '',
                username = ''
            )
        else:
            return AuthProfileDetails(
        )
        """

    def testAuthProfileDetails(self):
        """Test AuthProfileDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
