# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.finish_webauthn_auth_request import FinishWebauthnAuthRequest  # noqa: E501

class TestFinishWebauthnAuthRequest(unittest.TestCase):
    """FinishWebauthnAuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinishWebauthnAuthRequest:
        """Test FinishWebauthnAuthRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinishWebauthnAuthRequest`
        """
        model = FinishWebauthnAuthRequest()  # noqa: E501
        if include_optional:
            return FinishWebauthnAuthRequest(
                authenticator_response_data = '',
                aa_sig = '',
                auth_request_id = '',
                webauthn_client_id = ''
            )
        else:
            return FinishWebauthnAuthRequest(
        )
        """

    def testFinishWebauthnAuthRequest(self):
        """Test FinishWebauthnAuthRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
