# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.finish_new_webauthn_user_registration_request import FinishNewWebauthnUserRegistrationRequest  # noqa: E501

class TestFinishNewWebauthnUserRegistrationRequest(unittest.TestCase):
    """FinishNewWebauthnUserRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinishNewWebauthnUserRegistrationRequest:
        """Test FinishNewWebauthnUserRegistrationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinishNewWebauthnUserRegistrationRequest`
        """
        model = FinishNewWebauthnUserRegistrationRequest()  # noqa: E501
        if include_optional:
            return FinishNewWebauthnUserRegistrationRequest(
                aa_sig = '0',
                authenticator_response_data = autharmor_python.models.fido2_registration_data.fido2_registration_data(
                    id = '', 
                    attestation_object = '', 
                    client_data = '', ),
                webauthn_client_id = ''
            )
        else:
            return FinishNewWebauthnUserRegistrationRequest(
                aa_sig = '0',
                authenticator_response_data = autharmor_python.models.fido2_registration_data.fido2_registration_data(
                    id = '', 
                    attestation_object = '', 
                    client_data = '', ),
        )
        """

    def testFinishNewWebauthnUserRegistrationRequest(self):
        """Test FinishNewWebauthnUserRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
