# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.start_magiclink_email_registration_response import StartMagiclinkEmailRegistrationResponse  # noqa: E501

class TestStartMagiclinkEmailRegistrationResponse(unittest.TestCase):
    """StartMagiclinkEmailRegistrationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartMagiclinkEmailRegistrationResponse:
        """Test StartMagiclinkEmailRegistrationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartMagiclinkEmailRegistrationResponse`
        """
        model = StartMagiclinkEmailRegistrationResponse()  # noqa: E501
        if include_optional:
            return StartMagiclinkEmailRegistrationResponse(
                timeout_in_seconds = 56,
                timeout_utc_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return StartMagiclinkEmailRegistrationResponse(
        )
        """

    def testStartMagiclinkEmailRegistrationResponse(self):
        """Test StartMagiclinkEmailRegistrationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
