# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.secure_signed_message import SecureSignedMessage  # noqa: E501

class TestSecureSignedMessage(unittest.TestCase):
    """SecureSignedMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureSignedMessage:
        """Test SecureSignedMessage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureSignedMessage`
        """
        model = SecureSignedMessage()  # noqa: E501
        if include_optional:
            return SecureSignedMessage(
                signed_data = '',
                signature_data = autharmor_python.models.signature_data.signature_data(
                    hash_value = '', 
                    auth_method_usetype = 'biometric', 
                    signing_method = 'AuthArmor_ECDsa', 
                    auth_method = 'MobileDevice', 
                    hash_method = 'Sha256', ),
                signed_data_type = 'AuthResponse',
                signature_validation_details = None
            )
        else:
            return SecureSignedMessage(
        )
        """

    def testSecureSignedMessage(self):
        """Test SecureSignedMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
