# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.start_magiclink_email_auth_request import StartMagiclinkEmailAuthRequest  # noqa: E501

class TestStartMagiclinkEmailAuthRequest(unittest.TestCase):
    """StartMagiclinkEmailAuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartMagiclinkEmailAuthRequest:
        """Test StartMagiclinkEmailAuthRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartMagiclinkEmailAuthRequest`
        """
        model = StartMagiclinkEmailAuthRequest()  # noqa: E501
        if include_optional:
            return StartMagiclinkEmailAuthRequest(
                user_id = '',
                username = '',
                timeout_in_seconds = 56,
                origin_location_data = autharmor_python.models.location_data.location_data(
                    latitude = '', 
                    longitude = '', 
                    ip_address = '', ),
                action_name = '01',
                short_msg = '',
                auth_redirect_url = '',
                context_data = {
                    'key' : ''
                    },
                ip_address = '',
                user_agent = ''
            )
        else:
            return StartMagiclinkEmailAuthRequest(
        )
        """

    def testStartMagiclinkEmailAuthRequest(self):
        """Test StartMagiclinkEmailAuthRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
