# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_users_get(self) -> None:
        """Test case for v4_users_get

          Get Users  # noqa: E501
        """
        pass

    def test_v4_users_user_id_auth_history_get(self) -> None:
        """Test case for v4_users_user_id_auth_history_get

          Get Auth History for User  # noqa: E501
        """
        pass

    def test_v4_users_user_id_get(self) -> None:
        """Test case for v4_users_user_id_get

          Get User By Id  # noqa: E501
        """
        pass

    def test_v4_users_user_id_put(self) -> None:
        """Test case for v4_users_user_id_put

          Update User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
