# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.user_registrations_web_authn_api import UserRegistrationsWebAuthnApi  # noqa: E501


class TestUserRegistrationsWebAuthnApi(unittest.TestCase):
    """UserRegistrationsWebAuthnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserRegistrationsWebAuthnApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_users_registrations_webauthn_registration_id_finish_post(self) -> None:
        """Test case for v4_users_registrations_webauthn_registration_id_finish_post

          Finish WebAuthn Registration for new user  # noqa: E501
        """
        pass

    def test_v4_users_registrations_webauthn_registration_id_validate_post(self) -> None:
        """Test case for v4_users_registrations_webauthn_registration_id_validate_post

          Validate User Registration for WebAuthn  # noqa: E501
        """
        pass

    def test_v4_users_registrations_webauthn_start_post(self) -> None:
        """Test case for v4_users_registrations_webauthn_start_post

          Start WebAuthn Registration for new user  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_webauthn_registration_id_finish_post(self) -> None:
        """Test case for v4_users_user_id_registrations_webauthn_registration_id_finish_post

          Finish WebAuthn Registration for existing user  # noqa: E501
        """
        pass

    def test_v4_users_user_id_registrations_webauthn_start_post(self) -> None:
        """Test case for v4_users_user_id_registrations_webauthn_start_post

          Start WebAuthn Registration for existing user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
