# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.magiclink_email_registration_type import MagiclinkEmailRegistrationType  # noqa: E501

class TestMagiclinkEmailRegistrationType(unittest.TestCase):
    """MagiclinkEmailRegistrationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMagiclinkEmailRegistrationType(self):
        """Test MagiclinkEmailRegistrationType"""
        # inst = MagiclinkEmailRegistrationType()

if __name__ == '__main__':
    unittest.main()
