# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.start_new_webauthn_user_registration_request import StartNewWebauthnUserRegistrationRequest  # noqa: E501

class TestStartNewWebauthnUserRegistrationRequest(unittest.TestCase):
    """StartNewWebauthnUserRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartNewWebauthnUserRegistrationRequest:
        """Test StartNewWebauthnUserRegistrationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartNewWebauthnUserRegistrationRequest`
        """
        model = StartNewWebauthnUserRegistrationRequest()  # noqa: E501
        if include_optional:
            return StartNewWebauthnUserRegistrationRequest(
                username = '',
                email_address = '',
                timeout_in_seconds = 56,
                webauthn_client_id = '',
                attachment_type = 'Any',
                resident_key_requirement_type = 'required',
                user_verification_requirement_type = 'required'
            )
        else:
            return StartNewWebauthnUserRegistrationRequest(
        )
        """

    def testStartNewWebauthnUserRegistrationRequest(self):
        """Test StartNewWebauthnUserRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
