# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.get_user_response import GetUserResponse  # noqa: E501

class TestGetUserResponse(unittest.TestCase):
    """GetUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserResponse:
        """Test GetUserResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserResponse`
        """
        model = GetUserResponse()  # noqa: E501
        if include_optional:
            return GetUserResponse(
                enrolled_auth_methods = [
                    autharmor_python.models.enrolled_auth_method.enrolled_auth_method(
                        auth_method_name = '', 
                        auth_method_id = 56, 
                        auth_method_masked_info = '', )
                    ],
                user_id = '',
                email_address = '',
                username = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetUserResponse(
        )
        """

    def testGetUserResponse(self):
        """Test GetUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
