# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autharmor_python.api.auth_authenticator_api import AuthAuthenticatorApi  # noqa: E501


class TestAuthAuthenticatorApi(unittest.TestCase):
    """AuthAuthenticatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthAuthenticatorApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_v4_auth_authenticator_start_post(self) -> None:
        """Test case for v4_auth_authenticator_start_post

          Start auth request using Authenticator  # noqa: E501
        """
        pass

    def test_v4_auth_authenticator_validate_post(self) -> None:
        """Test case for v4_auth_authenticator_validate_post

         Validate auth request for Auth Armor Authenticator  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
