# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.hash_types import HashTypes  # noqa: E501

class TestHashTypes(unittest.TestCase):
    """HashTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHashTypes(self):
        """Test HashTypes"""
        # inst = HashTypes()

if __name__ == '__main__':
    unittest.main()
