# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.location_data import LocationData  # noqa: E501

class TestLocationData(unittest.TestCase):
    """LocationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationData:
        """Test LocationData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationData`
        """
        model = LocationData()  # noqa: E501
        if include_optional:
            return LocationData(
                latitude = '',
                longitude = '',
                ip_address = ''
            )
        else:
            return LocationData(
        )
        """

    def testLocationData(self):
        """Test LocationData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
