# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.validate_magiclink_email_auth_request import ValidateMagiclinkEmailAuthRequest  # noqa: E501

class TestValidateMagiclinkEmailAuthRequest(unittest.TestCase):
    """ValidateMagiclinkEmailAuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMagiclinkEmailAuthRequest:
        """Test ValidateMagiclinkEmailAuthRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMagiclinkEmailAuthRequest`
        """
        model = ValidateMagiclinkEmailAuthRequest()  # noqa: E501
        if include_optional:
            return ValidateMagiclinkEmailAuthRequest(
                auth_validation_token = '',
                auth_request_id = '',
                ip_address = '',
                user_agent = '',
                nonce = ''
            )
        else:
            return ValidateMagiclinkEmailAuthRequest(
        )
        """

    def testValidateMagiclinkEmailAuthRequest(self):
        """Test ValidateMagiclinkEmailAuthRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
