# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from autharmor_python.models.start_autharmor_authenticator_registration_new_user_response import StartAutharmorAuthenticatorRegistrationNewUserResponse  # noqa: E501

class TestStartAutharmorAuthenticatorRegistrationNewUserResponse(unittest.TestCase):
    """StartAutharmorAuthenticatorRegistrationNewUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartAutharmorAuthenticatorRegistrationNewUserResponse:
        """Test StartAutharmorAuthenticatorRegistrationNewUserResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartAutharmorAuthenticatorRegistrationNewUserResponse`
        """
        model = StartAutharmorAuthenticatorRegistrationNewUserResponse()  # noqa: E501
        if include_optional:
            return StartAutharmorAuthenticatorRegistrationNewUserResponse(
                username = '',
                registration_id = '',
                user_id = '',
                date_expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                auth_method = '',
                qr_code_data = '',
                registration_validation_token = ''
            )
        else:
            return StartAutharmorAuthenticatorRegistrationNewUserResponse(
        )
        """

    def testStartAutharmorAuthenticatorRegistrationNewUserResponse(self):
        """Test StartAutharmorAuthenticatorRegistrationNewUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
