# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class FinishWebauthnAuthRequest(BaseModel):
    """
    FinishWebauthnAuthRequest
    """
    authenticator_response_data: Optional[StrictStr] = None
    aa_sig: Optional[StrictStr] = None
    auth_request_id: Optional[StrictStr] = None
    webauthn_client_id: Optional[StrictStr] = None
    __properties = ["authenticator_response_data", "aa_sig", "auth_request_id", "webauthn_client_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FinishWebauthnAuthRequest:
        """Create an instance of FinishWebauthnAuthRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if authenticator_response_data (nullable) is None
        # and __fields_set__ contains the field
        if self.authenticator_response_data is None and "authenticator_response_data" in self.__fields_set__:
            _dict['authenticator_response_data'] = None

        # set to None if aa_sig (nullable) is None
        # and __fields_set__ contains the field
        if self.aa_sig is None and "aa_sig" in self.__fields_set__:
            _dict['aa_sig'] = None

        # set to None if auth_request_id (nullable) is None
        # and __fields_set__ contains the field
        if self.auth_request_id is None and "auth_request_id" in self.__fields_set__:
            _dict['auth_request_id'] = None

        # set to None if webauthn_client_id (nullable) is None
        # and __fields_set__ contains the field
        if self.webauthn_client_id is None and "webauthn_client_id" in self.__fields_set__:
            _dict['webauthn_client_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FinishWebauthnAuthRequest:
        """Create an instance of FinishWebauthnAuthRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FinishWebauthnAuthRequest.parse_obj(obj)

        _obj = FinishWebauthnAuthRequest.parse_obj({
            "authenticator_response_data": obj.get("authenticator_response_data"),
            "aa_sig": obj.get("aa_sig"),
            "auth_request_id": obj.get("auth_request_id"),
            "webauthn_client_id": obj.get("webauthn_client_id")
        })
        return _obj


