# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MagiclinkEmailRegistrationType(str, Enum):
    """
    MagiclinkEmailRegistrationType
    """

    """
    allowed enum values
    """
    NEW_USER = 'new_user'
    NEW_ENROLLMENT = 'new_enrollment'
    CHANGE_EMAIL = 'change_email'

    @classmethod
    def from_json(cls, json_str: str) -> MagiclinkEmailRegistrationType:
        """Create an instance of MagiclinkEmailRegistrationType from a JSON string"""
        return MagiclinkEmailRegistrationType(json.loads(json_str))


