# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SignedMessageType(str, Enum):
    """
    SignedMessageType
    """

    """
    allowed enum values
    """
    AUTHRESPONSE = 'AuthResponse'

    @classmethod
    def from_json(cls, json_str: str) -> SignedMessageType:
        """Create an instance of SignedMessageType from a JSON string"""
        return SignedMessageType(json.loads(json_str))


