# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SigningMethod(str, Enum):
    """
    SigningMethod
    """

    """
    allowed enum values
    """
    AUTH_ARMOR_EC_DSA = 'AuthArmor_ECDsa'
    FIDO_U2_F = 'FIDO_U2F'

    @classmethod
    def from_json(cls, json_str: str) -> SigningMethod:
        """Create an instance of SigningMethod from a JSON string"""
        return SigningMethod(json.loads(json_str))


