# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, constr

class StartAutharmorAutenticatorRegistrationNewUserRequest(BaseModel):
    """
    StartAutharmorAutenticatorRegistrationNewUserRequest
    """
    username: constr(strict=True, max_length=42, min_length=2) = Field(...)
    timeout_in_seconds: Optional[StrictInt] = None
    __properties = ["username", "timeout_in_seconds"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StartAutharmorAutenticatorRegistrationNewUserRequest:
        """Create an instance of StartAutharmorAutenticatorRegistrationNewUserRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if timeout_in_seconds (nullable) is None
        # and __fields_set__ contains the field
        if self.timeout_in_seconds is None and "timeout_in_seconds" in self.__fields_set__:
            _dict['timeout_in_seconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StartAutharmorAutenticatorRegistrationNewUserRequest:
        """Create an instance of StartAutharmorAutenticatorRegistrationNewUserRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StartAutharmorAutenticatorRegistrationNewUserRequest.parse_obj(obj)

        _obj = StartAutharmorAutenticatorRegistrationNewUserRequest.parse_obj({
            "username": obj.get("username"),
            "timeout_in_seconds": obj.get("timeout_in_seconds")
        })
        return _obj


