# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, StrictStr

class StartAddWebauthnToUserResponse(BaseModel):
    """
    StartAddWebauthnToUserResponse
    """
    fido2_json_options: Optional[Any] = None
    registration_id: Optional[StrictStr] = None
    aa_sig: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    __properties = ["fido2_json_options", "registration_id", "aa_sig", "user_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StartAddWebauthnToUserResponse:
        """Create an instance of StartAddWebauthnToUserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if fido2_json_options (nullable) is None
        # and __fields_set__ contains the field
        if self.fido2_json_options is None and "fido2_json_options" in self.__fields_set__:
            _dict['fido2_json_options'] = None

        # set to None if aa_sig (nullable) is None
        # and __fields_set__ contains the field
        if self.aa_sig is None and "aa_sig" in self.__fields_set__:
            _dict['aa_sig'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StartAddWebauthnToUserResponse:
        """Create an instance of StartAddWebauthnToUserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StartAddWebauthnToUserResponse.parse_obj(obj)

        _obj = StartAddWebauthnToUserResponse.parse_obj({
            "fido2_json_options": obj.get("fido2_json_options"),
            "registration_id": obj.get("registration_id"),
            "aa_sig": obj.get("aa_sig"),
            "user_id": obj.get("user_id")
        })
        return _obj


