# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class StartWebauthnAuthResponse(BaseModel):
    """
    StartWebauthnAuthResponse
    """
    fido2_json_options: Optional[StrictStr] = None
    auth_request_id: Optional[StrictStr] = None
    aa_guid: Optional[StrictStr] = None
    __properties = ["fido2_json_options", "auth_request_id", "aa_guid"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StartWebauthnAuthResponse:
        """Create an instance of StartWebauthnAuthResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if fido2_json_options (nullable) is None
        # and __fields_set__ contains the field
        if self.fido2_json_options is None and "fido2_json_options" in self.__fields_set__:
            _dict['fido2_json_options'] = None

        # set to None if aa_guid (nullable) is None
        # and __fields_set__ contains the field
        if self.aa_guid is None and "aa_guid" in self.__fields_set__:
            _dict['aa_guid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StartWebauthnAuthResponse:
        """Create an instance of StartWebauthnAuthResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StartWebauthnAuthResponse.parse_obj(obj)

        _obj = StartWebauthnAuthResponse.parse_obj({
            "fido2_json_options": obj.get("fido2_json_options"),
            "auth_request_id": obj.get("auth_request_id"),
            "aa_guid": obj.get("aa_guid")
        })
        return _obj


