# coding: utf-8

"""
    Autharmor

    Autharmor provides A Suite of Authentication and Authorization tools to enhance security and accelerate your business.

    The version of the OpenAPI document: v4
    Contact: support@autharmor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr
from autharmor_python.models.location_data import LocationData

class StartWebauthnAuthRequest(BaseModel):
    """
    StartWebauthnAuthRequest
    """
    user_id: Optional[StrictStr] = None
    username: Optional[StrictStr] = None
    timeout_in_seconds: Optional[StrictInt] = None
    origin_location_data: Optional[LocationData] = None
    action_name: Optional[StrictStr] = None
    short_msg: Optional[StrictStr] = None
    webauthn_client_id: Optional[StrictStr] = None
    ip_address: Optional[StrictStr] = None
    user_agent: Optional[StrictStr] = None
    nonce: Optional[StrictStr] = None
    __properties = ["user_id", "username", "timeout_in_seconds", "origin_location_data", "action_name", "short_msg", "webauthn_client_id", "ip_address", "user_agent", "nonce"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StartWebauthnAuthRequest:
        """Create an instance of StartWebauthnAuthRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of origin_location_data
        if self.origin_location_data:
            _dict['origin_location_data'] = self.origin_location_data.to_dict()
        # set to None if user_id (nullable) is None
        # and __fields_set__ contains the field
        if self.user_id is None and "user_id" in self.__fields_set__:
            _dict['user_id'] = None

        # set to None if username (nullable) is None
        # and __fields_set__ contains the field
        if self.username is None and "username" in self.__fields_set__:
            _dict['username'] = None

        # set to None if timeout_in_seconds (nullable) is None
        # and __fields_set__ contains the field
        if self.timeout_in_seconds is None and "timeout_in_seconds" in self.__fields_set__:
            _dict['timeout_in_seconds'] = None

        # set to None if action_name (nullable) is None
        # and __fields_set__ contains the field
        if self.action_name is None and "action_name" in self.__fields_set__:
            _dict['action_name'] = None

        # set to None if short_msg (nullable) is None
        # and __fields_set__ contains the field
        if self.short_msg is None and "short_msg" in self.__fields_set__:
            _dict['short_msg'] = None

        # set to None if webauthn_client_id (nullable) is None
        # and __fields_set__ contains the field
        if self.webauthn_client_id is None and "webauthn_client_id" in self.__fields_set__:
            _dict['webauthn_client_id'] = None

        # set to None if ip_address (nullable) is None
        # and __fields_set__ contains the field
        if self.ip_address is None and "ip_address" in self.__fields_set__:
            _dict['ip_address'] = None

        # set to None if user_agent (nullable) is None
        # and __fields_set__ contains the field
        if self.user_agent is None and "user_agent" in self.__fields_set__:
            _dict['user_agent'] = None

        # set to None if nonce (nullable) is None
        # and __fields_set__ contains the field
        if self.nonce is None and "nonce" in self.__fields_set__:
            _dict['nonce'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StartWebauthnAuthRequest:
        """Create an instance of StartWebauthnAuthRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StartWebauthnAuthRequest.parse_obj(obj)

        _obj = StartWebauthnAuthRequest.parse_obj({
            "user_id": obj.get("user_id"),
            "username": obj.get("username"),
            "timeout_in_seconds": obj.get("timeout_in_seconds"),
            "origin_location_data": LocationData.from_dict(obj.get("origin_location_data")) if obj.get("origin_location_data") is not None else None,
            "action_name": obj.get("action_name"),
            "short_msg": obj.get("short_msg"),
            "webauthn_client_id": obj.get("webauthn_client_id"),
            "ip_address": obj.get("ip_address"),
            "user_agent": obj.get("user_agent"),
            "nonce": obj.get("nonce")
        })
        return _obj


