# coding: utf-8

"""
    Autharmor

    Auth Armor - Auth Anywhere API

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class ValidateAutharmorAuthenticatorAuthRequest(BaseModel):
    """
    ValidateAutharmorAuthenticatorAuthRequest
    """
    auth_validation_token: Optional[StrictStr] = None
    auth_request_id: Optional[StrictStr] = None
    ip_address: Optional[StrictStr] = None
    user_agent: Optional[StrictStr] = None
    nonce: Optional[StrictStr] = None
    __properties = ["auth_validation_token", "auth_request_id", "ip_address", "user_agent", "nonce"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ValidateAutharmorAuthenticatorAuthRequest:
        """Create an instance of ValidateAutharmorAuthenticatorAuthRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if auth_validation_token (nullable) is None
        # and __fields_set__ contains the field
        if self.auth_validation_token is None and "auth_validation_token" in self.__fields_set__:
            _dict['auth_validation_token'] = None

        # set to None if auth_request_id (nullable) is None
        # and __fields_set__ contains the field
        if self.auth_request_id is None and "auth_request_id" in self.__fields_set__:
            _dict['auth_request_id'] = None

        # set to None if ip_address (nullable) is None
        # and __fields_set__ contains the field
        if self.ip_address is None and "ip_address" in self.__fields_set__:
            _dict['ip_address'] = None

        # set to None if user_agent (nullable) is None
        # and __fields_set__ contains the field
        if self.user_agent is None and "user_agent" in self.__fields_set__:
            _dict['user_agent'] = None

        # set to None if nonce (nullable) is None
        # and __fields_set__ contains the field
        if self.nonce is None and "nonce" in self.__fields_set__:
            _dict['nonce'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ValidateAutharmorAuthenticatorAuthRequest:
        """Create an instance of ValidateAutharmorAuthenticatorAuthRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ValidateAutharmorAuthenticatorAuthRequest.parse_obj(obj)

        _obj = ValidateAutharmorAuthenticatorAuthRequest.parse_obj({
            "auth_validation_token": obj.get("auth_validation_token"),
            "auth_request_id": obj.get("auth_request_id"),
            "ip_address": obj.get("ip_address"),
            "user_agent": obj.get("user_agent"),
            "nonce": obj.get("nonce")
        })
        return _obj


